apiVersion: v1
kind: Service
metadata:
  name: flaskweb-service
spec:
  type: NodePort
  selector:
    app: flaskweb
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007