apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: flaskweb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaskweb-deployment
  minReplicas: 1
  maxReplicas: 8
  behavior:
   scaleDown:
     stabilizationWindowSeconds: 600 
   scaleUp:
     stabilizationWindowSeconds: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
       

